#nullable enable
using Broiler.JavaScript.ExpressionCompiler;
using Broiler.JavaScript.Storage;
using Broiler.JavaScript.Runtime;

namespace Broiler.JavaScript.Engine.Core;

[JSRegistrationGenerator]
internal static partial class Names
{
    public static void RegisterGeneratedClasses(this JSObject context) => RegisterAll(context);

    // ── Names formerly generated by JSFunction (now in BuiltIns assembly) ──
    // Kept here so that the generated JSFunction.g.cs code (whose namespace is
    // Broiler.JavaScript.Core.Core.Function) can resolve Names.* via the
    // parent namespace Broiler.JavaScript.Core.Core.
    public static readonly KeyString Function = "Function";
    public static readonly KeyString valueOf = "valueOf";
    public static readonly KeyString call = "call";
    public static readonly KeyString apply = "apply";
    public static readonly KeyString bind = "bind";
    public static readonly KeyString toString = "toString";
}
