using Broiler.JavaScript.Runtime;
using Broiler.JavaScript.Storage;

namespace Broiler.JavaScript.Engine.Core;

/// <summary>
/// Creates the JavaScript <c>Object</c> constructor and wires its prototype
/// methods and static methods.  This was formerly source-generated by the
/// <c>JSClassGenerator</c> as <c>JSObject.CreateClass</c>.  Because
/// <c>JSObject</c> now lives in the Runtime assembly (which cannot reference
/// Core), the factory is provided here and exposed via
/// <see cref="JSEngine.CreateObjectClass"/>.
///
/// Uses <see cref="JSValue.CreateFunction(JSFunctionDelegate, string, string, int, bool)"/>
/// factory delegates instead of directly constructing <c>JSFunction</c>,
/// because <c>JSFunction</c> now lives in the BuiltIns assembly.
/// </summary>
internal static class ObjectClassFactory
{
    internal static JSValue CreateObjectClass(JSObject context, bool register)
    {
        KeyString objectKey = "Object";

        var classValue = JSValue.CreateFunction(JSObject.Constructor, "Object", "function Object() { [native code] }");
        var @class = (JSObject)classValue;

        if (register)
            context[objectKey] = classValue;

        var prototype = ((IJSFunction)classValue).Prototype as JSObject;

        // ── Prototype methods ───────────────────────────────────────

        // propertyIsEnumerable
        prototype.FastAddValue(
            (KeyString)"propertyIsEnumerable",
            JSValue.CreateFunction(JSObject.PropertyIsEnumerable, "propertyIsEnumerable",
                "function propertyIsEnumerable() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // toString
        prototype.FastAddValue(
            (KeyString)"toString",
            JSValue.CreateFunction(JSObject.ToString, "toString",
                "function toString() { [native] }", 0, false),
            JSPropertyAttributes.ConfigurableValue);

        // __proto__ (get/set property)
        prototype.FastAddProperty(
            (KeyString)"__proto__",
            JSValue.CreateFunction((in Arguments a) =>
                a.This is JSObject @this
                    ? @this.ObjectPrototype
                    : throw JSEngine.NewTypeError("Failed to convert this to JSObject"),
                "get __proto__"),
            JSValue.CreateFunction((in Arguments a) =>
            {
                if (a.This is JSObject @this)
                    @this.ObjectPrototype = JSValueToClrConverter.GetAsOrThrow<JSValue>(a[0], "__proto__");
                else
                    throw JSEngine.NewTypeError("Failed to convert this to JSObject");
                return JSUndefined.Value;
            },
                "set __proto__"),
            JSPropertyAttributes.ConfigurableProperty);

        // hasOwnProperty
        prototype.FastAddValue(
            (KeyString)"hasOwnProperty",
            JSValue.CreateFunction(JSObject.HasOwnProperty, "hasOwnProperty",
                "function hasOwnProperty() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // valueOf
        prototype.FastAddValue(
            (KeyString)"valueOf",
            JSValue.CreateFunction(JSObject.ValueOf, "valueOf",
                "function valueOf() { [native] }", 0, false),
            JSPropertyAttributes.ConfigurableValue);

        // isPrototypeOf
        prototype.FastAddValue(
            (KeyString)"isPrototypeOf",
            JSValue.CreateFunction(JSObject.IsPrototypeOf, "isPrototypeOf",
                "function isPrototypeOf() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // ── Static methods ──────────────────────────────────────────

        // create
        @class.FastAddValue(
            (KeyString)"create",
            JSValue.CreateFunction(JSObject.StaticCreate, "create",
                "function create() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // assign
        @class.FastAddValue(
            (KeyString)"assign",
            JSValue.CreateFunction(JSObject.Assign, "assign",
                "function assign() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // defineProperties
        @class.FastAddValue(
            (KeyString)"defineProperties",
            JSValue.CreateFunction(JSObject.DefineProperties, "defineProperties",
                "function defineProperties() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // defineProperty
        @class.FastAddValue(
            (KeyString)"defineProperty",
            JSValue.CreateFunction(JSObject.DefineProperty, "defineProperty",
                "function defineProperty() { [native] }", 3, false),
            JSPropertyAttributes.ConfigurableValue);

        // entries
        @class.FastAddValue(
            (KeyString)"entries",
            JSValue.CreateFunction(JSObject.GetEntries, "entries",
                "function entries() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // freeze
        @class.FastAddValue(
            (KeyString)"freeze",
            JSValue.CreateFunction(JSObject.Freeze, "freeze",
                "function freeze() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // fromEntries
        @class.FastAddValue(
            (KeyString)"fromEntries",
            JSValue.CreateFunction(JSObject.FromEntries, "fromEntries",
                "function fromEntries() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // preventExtensions
        @class.FastAddValue(
            (KeyString)"preventExtensions",
            JSValue.CreateFunction(JSObject.PreventExtensions, "preventExtensions",
                "function preventExtensions() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // seal
        @class.FastAddValue(
            (KeyString)"seal",
            JSValue.CreateFunction(JSObject.Seal, "seal",
                "function seal() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // setPrototypeOf
        @class.FastAddValue(
            (KeyString)"setPrototypeOf",
            JSValue.CreateFunction(JSObject.SetPrototypeOf, "setPrototypeOf",
                "function setPrototypeOf() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // groupBy
        @class.FastAddValue(
            (KeyString)"groupBy",
            JSValue.CreateFunction(JSObject.GroupBy, "groupBy",
                "function groupBy() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // ── Static introspection methods ────────────────────────────

        // entries (static, overwrites previous)
        @class.FastAddValue(
            (KeyString)"entries",
            JSValue.CreateFunction(JSObject.StaticEntries, "entries",
                "function entries() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // is
        @class.FastAddValue(
            (KeyString)"is",
            JSValue.CreateFunction(JSObject.Is, "is",
                "function is() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // isExtensible
        @class.FastAddValue(
            (KeyString)"isExtensible",
            JSValue.CreateFunction(JSObject.IsExtensible, "isExtensible",
                "function isExtensible() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // isFrozen
        @class.FastAddValue(
            (KeyString)"isFrozen",
            JSValue.CreateFunction(JSObject.IsFrozen, "isFrozen",
                "function isFrozen() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // isSealed
        @class.FastAddValue(
            (KeyString)"isSealed",
            JSValue.CreateFunction(JSObject.IsSealed, "isSealed",
                "function isSealed() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // keys
        @class.FastAddValue(
            (KeyString)"keys",
            JSValue.CreateFunction(JSObject.Keys, "keys",
                "function keys() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // values
        @class.FastAddValue(
            (KeyString)"values",
            JSValue.CreateFunction(JSObject.Values, "values",
                "function values() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyDescriptor
        @class.FastAddValue(
            (KeyString)"getOwnPropertyDescriptor",
            JSValue.CreateFunction(JSObject.GetOwnPropertyDescriptor, "getOwnPropertyDescriptor",
                "function getOwnPropertyDescriptor() { [native] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyDescriptors
        @class.FastAddValue(
            (KeyString)"getOwnPropertyDescriptors",
            JSValue.CreateFunction(JSObject.GetOwnPropertyDescriptors, "getOwnPropertyDescriptors",
                "function getOwnPropertyDescriptors() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyNames
        @class.FastAddValue(
            (KeyString)"getOwnPropertyNames",
            JSValue.CreateFunction(JSObject.GetOwnPropertyNames, "getOwnPropertyNames",
                "function getOwnPropertyNames() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertySymbols
        @class.FastAddValue(
            (KeyString)"getOwnPropertySymbols",
            JSValue.CreateFunction(JSObject.GetOwnPropertySymbols, "getOwnPropertySymbols",
                "function getOwnPropertySymbols() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getPrototypeOf
        @class.FastAddValue(
            (KeyString)"getPrototypeOf",
            JSValue.CreateFunction(JSObject.GetPrototypeOf, "getPrototypeOf",
                "function getPrototypeOf() { [native] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        return classValue;
    }
}
