using System;
using System.Linq.Expressions;

namespace Broiler.JavaScript.ExpressionCompiler.Converters;

public abstract class LinqMap<T> : StackGuard<T, Expression> where T : class
{
    public override T VisitIn(Expression exp)
    {
        if (exp == null)
            return default;

        return exp.NodeType switch
        {
            ExpressionType.Add => VisitAdd(exp as BinaryExpression),
            ExpressionType.AddAssign => VisitAddAssign(exp as BinaryExpression),
            ExpressionType.AddAssignChecked => VisitAddAssignChecked(exp as BinaryExpression),
            ExpressionType.AddChecked => VisitAddChecked(exp as BinaryExpression),
            ExpressionType.And => VisitAnd(exp as BinaryExpression),
            ExpressionType.AndAlso => VisitAndAlso(exp as BinaryExpression),
            ExpressionType.AndAssign => VisitAndAssign(exp as BinaryExpression),
            ExpressionType.ArrayIndex => VisitArrayIndex(exp as BinaryExpression),
            ExpressionType.ArrayLength => VisitArrayLength(exp as UnaryExpression),
            ExpressionType.Assign => VisitAssign(exp as BinaryExpression),
            ExpressionType.Block => VisitBlock(exp as BlockExpression),
            ExpressionType.Call => VisitCall(exp as MethodCallExpression),
            ExpressionType.Coalesce => VisitCoalesce(exp as BinaryExpression),
            ExpressionType.Conditional => VisitConditional(exp as ConditionalExpression),
            ExpressionType.Constant => VisitConstant(exp as ConstantExpression),
            ExpressionType.Convert => VisitConvert(exp as UnaryExpression),
            ExpressionType.ConvertChecked => VisitConvertChecked(exp as UnaryExpression),
            ExpressionType.DebugInfo => VisitDebugInfo(exp as ConstantExpression),
            ExpressionType.Decrement => VisitDecrement(exp as UnaryExpression),
            ExpressionType.Default => VisitDefault(exp as DefaultExpression),
            ExpressionType.Divide => VisitDivide(exp as BinaryExpression),
            ExpressionType.DivideAssign => VisitDivideAssign(exp as BinaryExpression),
            ExpressionType.Dynamic => VisitDynamic(exp as DynamicExpression),
            ExpressionType.Equal => VisitEqual(exp as BinaryExpression),
            ExpressionType.ExclusiveOr => VisitExclusiveOr(exp as BinaryExpression),
            ExpressionType.ExclusiveOrAssign => VisitExclusiveOrAssign(exp as BinaryExpression),
            ExpressionType.Extension => VisitExtension(exp),
            ExpressionType.Goto => VisitGoto(exp as GotoExpression),
            ExpressionType.GreaterThan => VisitGreaterThan(exp as BinaryExpression),
            ExpressionType.GreaterThanOrEqual => VisitGreaterThanOrEqual(exp as BinaryExpression),
            ExpressionType.Increment => VisitIncrement(exp as UnaryExpression),
            ExpressionType.Index => VisitIndex(exp as IndexExpression),
            ExpressionType.Invoke => VisitInvoke(exp as InvocationExpression),
            ExpressionType.IsFalse => VisitIsFalse(exp as UnaryExpression),
            ExpressionType.IsTrue => VisitIsTrue(exp as UnaryExpression),
            ExpressionType.Label => VisitLabel(exp as LabelExpression),
            ExpressionType.Lambda => VisitLambda(exp as LambdaExpression),
            ExpressionType.LeftShift => VisitLeftShift(exp as BinaryExpression),
            ExpressionType.LeftShiftAssign => VisitLeftShiftAssign(exp as BinaryExpression),
            ExpressionType.LessThan => VisitLessThan(exp as BinaryExpression),
            ExpressionType.LessThanOrEqual => VisitLessThanOrEqual(exp as BinaryExpression),
            ExpressionType.ListInit => VisitListInit(exp as ListInitExpression),
            ExpressionType.Loop => VisitLoop(exp as LoopExpression),
            ExpressionType.MemberAccess => VisitMemberAccess(exp as MemberExpression),
            ExpressionType.MemberInit => VisitMemberInit(exp as MemberInitExpression),
            ExpressionType.Modulo => VisitModulo(exp as BinaryExpression),
            ExpressionType.ModuloAssign => VisitModuloAssign(exp as BinaryExpression),
            ExpressionType.Multiply => VisitMultiply(exp as BinaryExpression),
            ExpressionType.MultiplyAssign => VisitMultiplyAssign(exp as BinaryExpression),
            ExpressionType.MultiplyAssignChecked => VisitMultiplyAssignChecked(exp as BinaryExpression),
            ExpressionType.MultiplyChecked => VisitMultiplyChecked(exp as BinaryExpression),
            ExpressionType.Negate => VisitNegate(exp as UnaryExpression),
            ExpressionType.NegateChecked => VisitNegateChecked(exp as BinaryExpression),
            ExpressionType.New => VisitNew(exp as NewExpression),
            ExpressionType.NewArrayBounds => VisitNewArrayBounds(exp as NewArrayExpression),
            ExpressionType.NewArrayInit => VisitNewArrayInit(exp as NewArrayExpression),
            ExpressionType.Not => VisitNot(exp as UnaryExpression),
            ExpressionType.NotEqual => VisitNotEqual(exp as BinaryExpression),
            ExpressionType.OnesComplement => VisitOnesComplement(exp as UnaryExpression),
            ExpressionType.Or => VisitOr(exp as BinaryExpression),
            ExpressionType.OrAssign => VisitOrAssign(exp as BinaryExpression),
            ExpressionType.OrElse => VisitOrElse(exp as BinaryExpression),
            ExpressionType.Parameter => VisitParameter(exp as ParameterExpression),
            ExpressionType.PostDecrementAssign => VisitPostDecrementAssign(exp as UnaryExpression),
            ExpressionType.PostIncrementAssign => VisitPostIncrementAssign(exp as UnaryExpression),
            ExpressionType.Power => VisitPower(exp as BinaryExpression),
            ExpressionType.PowerAssign => VisitPowerAssign(exp as BinaryExpression),
            ExpressionType.PreDecrementAssign => VisitPreDecrementAssign(exp as UnaryExpression),
            ExpressionType.PreIncrementAssign => VisitPreIncrementAssign(exp as UnaryExpression),
            ExpressionType.Quote => VisitQuote(exp as UnaryExpression),
            ExpressionType.RightShift => VisitRightShift(exp as BinaryExpression),
            ExpressionType.RightShiftAssign => VisitRightShiftAssign(exp as BinaryExpression),
            ExpressionType.RuntimeVariables => VisitRuntimeVariables(exp as RuntimeVariablesExpression),
            ExpressionType.Subtract => VisitSubtract(exp as BinaryExpression),
            ExpressionType.SubtractAssign => VisitSubtractAssign(exp as BinaryExpression),
            ExpressionType.SubtractAssignChecked => VisitSubtractAssignChecked(exp as BinaryExpression),
            ExpressionType.SubtractChecked => VisitSubtractChecked(exp as BinaryExpression),
            ExpressionType.Switch => VisitSwitch(exp as SwitchExpression),
            ExpressionType.Throw => VisitThrow(exp as UnaryExpression),
            ExpressionType.Try => VisitTry(exp as TryExpression),
            ExpressionType.TypeAs => VisitTypeAs(exp as UnaryExpression),
            ExpressionType.TypeEqual => VisitTypeEqual(exp as TypeBinaryExpression),
            ExpressionType.TypeIs => VisitTypeIs(exp as TypeBinaryExpression),
            ExpressionType.UnaryPlus => VisitUnaryPlus(exp as UnaryExpression),
            ExpressionType.Unbox => VisitUnbox(exp as UnaryExpression),
            _ => throw new NotSupportedException(),
        };
    }

    protected abstract T VisitUnbox(UnaryExpression node);
    protected abstract T VisitUnaryPlus(UnaryExpression node);
    protected abstract T VisitTypeIs(TypeBinaryExpression node);
    protected abstract T VisitTypeEqual(TypeBinaryExpression node);
    protected abstract T VisitTypeAs(UnaryExpression node);
    protected abstract T VisitTry(TryExpression node);
    protected abstract T VisitThrow(UnaryExpression node);
    protected abstract T VisitSwitch(SwitchExpression node);
    protected abstract T VisitSubtractChecked(BinaryExpression node);
    protected abstract T VisitSubtractAssignChecked(BinaryExpression node);
    protected abstract T VisitSubtractAssign(BinaryExpression node);
    protected abstract T VisitSubtract(BinaryExpression node);
    protected abstract T VisitRuntimeVariables(RuntimeVariablesExpression node);
    protected abstract T VisitRightShiftAssign(BinaryExpression node);
    protected abstract T VisitRightShift(BinaryExpression node);
    protected abstract T VisitQuote(UnaryExpression node);
    protected abstract T VisitPreIncrementAssign(UnaryExpression node);
    protected abstract T VisitPreDecrementAssign(UnaryExpression node);
    protected abstract T VisitPowerAssign(BinaryExpression node);
    protected abstract T VisitPower(BinaryExpression node);
    protected abstract T VisitPostIncrementAssign(UnaryExpression node);
    protected abstract T VisitPostDecrementAssign(UnaryExpression node);
    protected abstract T VisitParameter(ParameterExpression node);
    protected abstract T VisitOrElse(BinaryExpression node);
    protected abstract T VisitOrAssign(BinaryExpression node);
    protected abstract T VisitOr(BinaryExpression node);
    protected abstract T VisitOnesComplement(UnaryExpression node);
    protected abstract T VisitNotEqual(BinaryExpression node);
    protected abstract T VisitNot(UnaryExpression node);
    protected abstract T VisitNewArrayInit(NewArrayExpression node);
    protected abstract T VisitNewArrayBounds(NewArrayExpression node);
    protected abstract T VisitNew(NewExpression node);
    protected abstract T VisitNegateChecked(BinaryExpression node);
    protected abstract T VisitNegate(UnaryExpression node);
    protected abstract T VisitMultiplyChecked(BinaryExpression node);
    protected abstract T VisitMultiplyAssignChecked(BinaryExpression node);
    protected abstract T VisitMultiplyAssign(BinaryExpression node);
    protected abstract T VisitMultiply(BinaryExpression node);
    protected abstract T VisitModuloAssign(BinaryExpression node);
    protected abstract T VisitModulo(BinaryExpression node);
    protected abstract T VisitMemberInit(MemberInitExpression node);
    protected abstract T VisitMemberAccess(MemberExpression node);
    protected abstract T VisitLoop(LoopExpression node);
    protected abstract T VisitListInit(ListInitExpression node);
    protected abstract T VisitLessThanOrEqual(BinaryExpression node);
    protected abstract T VisitLessThan(BinaryExpression node);
    protected abstract T VisitLeftShiftAssign(BinaryExpression node);
    protected abstract T VisitLeftShift(BinaryExpression node);
    protected abstract T VisitLambda(LambdaExpression node);
    protected abstract T VisitLabel(LabelExpression node);
    protected abstract T VisitIsTrue(UnaryExpression node);
    protected abstract T VisitIsFalse(UnaryExpression node);
    protected abstract T VisitInvoke(InvocationExpression node);
    protected abstract T VisitIndex(IndexExpression node);
    protected abstract T VisitIncrement(UnaryExpression node);
    protected abstract T VisitGreaterThanOrEqual(BinaryExpression node);
    protected abstract T VisitGreaterThan(BinaryExpression node);
    protected abstract T VisitGoto(GotoExpression node);
    protected abstract T VisitExtension(Expression exp);
    protected abstract T VisitExclusiveOrAssign(BinaryExpression node);
    protected abstract T VisitExclusiveOr(BinaryExpression node);
    protected abstract T VisitEqual(BinaryExpression node);
    protected abstract T VisitDynamic(DynamicExpression node);
    protected abstract T VisitDivideAssign(BinaryExpression node);
    protected abstract T VisitDivide(BinaryExpression node);
    protected abstract T VisitDefault(DefaultExpression node);
    protected abstract T VisitDecrement(UnaryExpression node);
    protected abstract T VisitDebugInfo(ConstantExpression node);
    protected abstract T VisitConvertChecked(UnaryExpression node);
    protected abstract T VisitConvert(UnaryExpression node);
    protected abstract T VisitConstant(ConstantExpression node);
    protected abstract T VisitConditional(ConditionalExpression node);
    protected abstract T VisitCoalesce(BinaryExpression node);
    protected abstract T VisitCall(MethodCallExpression node);
    protected abstract T VisitBlock(BlockExpression node);
    protected abstract T VisitAssign(BinaryExpression node);
    protected abstract T VisitArrayLength(UnaryExpression node);
    protected abstract T VisitArrayIndex(BinaryExpression node);
    protected abstract T VisitAndAssign(BinaryExpression node);
    protected abstract T VisitAndAlso(BinaryExpression node);
    protected abstract T VisitAnd(BinaryExpression node);
    protected abstract T VisitAddChecked(BinaryExpression node);
    protected abstract T VisitAddAssignChecked(BinaryExpression node);
    protected abstract T VisitAddAssign(BinaryExpression node);
    protected abstract T VisitAdd(BinaryExpression node);
}
