using Broiler.JavaScript.Ast.Misc;
using Broiler.JavaScript.BuiltIns;
using Broiler.JavaScript.Core.Core;
using Broiler.JavaScript.Engine;
using Broiler.JavaScript.Modules;
using Broiler.JavaScript.Parser;
using Broiler.JavaScript.Runtime;
using Broiler.JavaScript.Storage;

namespace Broiler.JavaScript.Integration.Tests;

public class IntegrationTests
{
    [Fact]
    public void FullPipeline_ParseCompileExecute()
    {
        // Parse
        var code = "2 + 3";
        var stream = new FastTokenStream(new StringSpan(code));
        var parser = new FastParser(stream);
        var program = parser.ParseProgram();
        Assert.NotNull(program);

        // Compile and Execute via JSContext
        using var ctx = new JSContext();
        var result = ctx.Eval(code);
        Assert.Equal(5.0, result.DoubleValue);
    }

    [Fact]
    public void CompilerRegistration_Works()
    {
        // Creating a JSContext triggers ModuleInitializer chain
        // which registers FastCompiler, BuiltIns, and CLR interop
        using var ctx = new JSContext();
        var result = ctx.Eval("typeof undefined");
        Assert.Equal("undefined", result.ToString());
    }

    [Fact]
    public void BuiltInsRegistration_Works()
    {
        // Ensure the BuiltIns assembly is loaded so its ModuleInitializer fires
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // WeakRef should be available after BuiltIns registration
        var result = ctx.Eval("typeof WeakRef");
        Assert.Equal("function", result.ToString());
    }

    [Fact]
    public void ClrRegistration_Works()
    {
        using var ctx = new JSContext();
        // CLR interop should be functional after registration
        Assert.NotNull(JSEngine.Current);
    }

    [Fact]
    public void TypeLocation_ResolvesCorrectly()
    {
        // Types live directly in their target assemblies after refactoring
        var jsValueType = typeof(JSValue);
        Assert.NotNull(jsValueType);
        Assert.Equal("Broiler.JavaScript.Runtime", jsValueType.Namespace);
    }

    [Fact]
    public void JSModuleContext_WithCompiler_Works()
    {
        var moduleCtx = new JSModuleContext();
        Assert.NotNull(moduleCtx);
        // Module context should work with the registered compiler
        var exports = new JSObject();
        moduleCtx.RegisterModule(
            KeyStrings.GetOrCreate(new StringSpan("test")),
            exports);
    }

    [Fact]
    public void SourceGenerator_IndependentPerAssembly()
    {
        // Both Core and BuiltIns assemblies should have independent Names classes
        // generated by JSClassGenerator. Verify both assemblies load correctly.
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // This exercises code paths in both Core and BuiltIns assemblies
        var result = ctx.Eval("typeof WeakRef");
        Assert.Equal("function", result.ToString());
    }

    // ── M2: Cross-assembly wiring tests ──────────────────────────────

    [Fact]
    public void M2_Math_RegisteredFromBuiltIns()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // Math should be registered from the BuiltIns assembly
        var result = ctx.Eval("typeof Math");
        Assert.Equal("object", result.ToString());
    }

    [Fact]
    public void M2_Math_MethodsWorkAcrossAssembly()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval("Math.abs(-5) + Math.floor(3.7) + Math.ceil(1.1)");
        Assert.Equal(10.0, result.DoubleValue);
    }

    [Fact]
    public void M2_Reflect_RegisteredFromBuiltIns()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval("typeof Reflect");
        Assert.Equal("object", result.ToString());
    }

    [Fact]
    public void M2_Reflect_MethodsWorkAcrossAssembly()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval(@"
            var obj = { a: 1, b: 2, c: 3 };
            Reflect.ownKeys(obj).length;
        ");
        Assert.Equal(3.0, result.DoubleValue);
    }

    [Fact]
    public void M2_Proxy_RegisteredFromBuiltIns()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval("typeof Proxy");
        Assert.Equal("function", result.ToString());
    }

    [Fact]
    public void M2_Proxy_ConstructAndTraps()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval(@"
            var handler = {
                get: function(target, name) {
                    return name in target ? target[name] : 'default';
                }
            };
            var p = new Proxy({ x: 10 }, handler);
            p.x + '|' + p.y;
        ");
        Assert.Equal("10|default", result.ToString());
    }

    [Fact]
    public void M2_Console_RegisteredFromBuiltIns()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Clr.DefaultClrInterop).TypeHandle);
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        var result = ctx.Eval("typeof console");
        Assert.Equal("object", result.ToString());
    }

    [Fact]
    public void M2_Console_LogWarnErrorWork()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Clr.DefaultClrInterop).TypeHandle);
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // Verify all three console methods are callable without error
        var result = ctx.Eval(@"
            typeof console.log + '|' + typeof console.warn + '|' + typeof console.error;
        ");
        Assert.Equal("function|function|function", result.ToString());
    }

    [Fact]
    public void M2_ConsoleFactory_WiredByModuleInitializer()
    {
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.BuiltIns.Weak.JSWeakRef).TypeHandle);
        Assert.NotNull(DefaultBuiltInRegistry.ConsoleFactory);
    }

    // ── BuiltInsAssemblyInitializer eager loading tests ──────────────

    [Fact]
    public void BuiltInsInitializer_DelegatesWired_AfterRegister()
    {
        // Verify that DefaultBuiltInRegistry.Register() triggers
        // BuiltInsAssemblyInitializer.Initialize() via EnsureBuiltInsAssemblyLoaded(),
        // ensuring all delegates are wired even without explicit assembly loading.
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Clr.DefaultClrInterop).TypeHandle);
        using var ctx = new JSContext();

        // These delegates are set by BuiltInsAssemblyInitializer.Initialize().
        // If Initialize was not called, they would be null.
        Assert.NotNull(DefaultBuiltInRegistry.AdditionalRegistrations);
        Assert.NotNull(DefaultBuiltInRegistry.ConsoleFactory);
        Assert.NotNull(DefaultBuiltInRegistry.StructuredCloneExtension);
        Assert.NotNull(DefaultBuiltInRegistry.IteratorPrototypeSetup);
    }

    [Fact]
    public void BuiltInsInitializer_FactoryDelegates_WiredAfterRegister()
    {
        // Verify factory delegates on JSValue are wired by Initialize().
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Clr.DefaultClrInterop).TypeHandle);
        using var ctx = new JSContext();

        // Use the public factory methods which delegate to the internal factories.
        // If the factories were not wired, these would throw NullReferenceException.
        Assert.NotNull(JSValue.CreateBigIntFromStringFactory);
        var bigInt = JSValue.CreateBigInt(0);
        Assert.NotNull(bigInt);
        var dec = JSValue.CreateDecimal(0m);
        Assert.NotNull(dec);
    }
}
