using Broiler.JavaScript.ExpressionCompiler;
using Broiler.JavaScript.Storage;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Broiler.JavaScript.Runtime;


internal delegate void PropertyChangedEventHandler(JSObject sender, (uint keyString, uint index, IJSSymbol symbol) index);

[JSBaseClass("Object")]
public partial class JSObject : JSValue
{
    private IJSPrototype currentPrototype;
    protected bool HasIterator = false;

    /// <summary>
    /// Returns the Object prototype from the current execution context.
    /// This was formerly source-generated by JSFunctionGenerator; now uses
    /// the <see cref="GetCurrentObjectPrototype"/> delegate wired by Core.
    /// </summary>
    protected override JSValue GetCurrentPrototype() => GetCurrentObjectPrototype?.Invoke();

    /// <summary>
    /// Factory delegate for creating prototype instances.
    /// Wired by BuiltInsAssemblyInitializer at startup.
    /// </summary>
    internal static Func<JSObject, IJSPrototype> CreatePrototype;

    // ── Factory delegates for abstracting Core dependencies ──
    // These are wired by CoreAssemblyInitializer so that JSObject
    // (in Runtime) can access Core functionality without a direct reference.
    internal new static Func<string, Exception> NewTypeError;
    internal static Func<JSObject> GetCurrentObjectPrototype;
    internal static Func<string, double> CoerceToNumber;
    internal static Func<JSValue, JSValue> CreatePrimitiveObject;

    // Error message constants (originally from JSException in Core)
    internal const string Cannot_convert_undefined_or_null_to_object = "Cannot convert undefined or null to object";
    internal const string Parameter_is_not_an_object = "Parameter is not an object";
    internal static string NotIterable(object name) => $"{name} is not iterable";
    internal static string NotEntry(object name) => $"Iterator value {name} is an entry object";

    // CLR conversion delegates (originally in CoreInternalHelpers)
    internal delegate bool TryConvertDelegate(JSValue value, Type type, out object result);
    internal static TryConvertDelegate TryGetClrEnumeratorFunc;
    internal delegate bool TryUnmarshalDelegate(JSObject obj, Type type, out object result);
    internal static TryUnmarshalDelegate TryUnmarshalObject;

    public override JSValue BasePrototypeObject
    {
        set
        {
            prototypeChain = (value as JSObject)?.PrototypeObject;
            PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));
            currentPrototype?.Dirty();
        }
    }

    internal IJSPrototype PrototypeObject
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => currentPrototype ??= CreatePrototype(this);
    }

    internal void Dirty() => PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));

    internal ObjectStatus status = ObjectStatus.None;

    // internal long version = 0;
    internal event PropertyChangedEventHandler PropertyChanged;
    private ElementArray elements;
    private PropertySequence ownProperties;
    private SAUint32Map<JSProperty> symbols;
    private long? uid;

    private static long NextID = 0;
    internal long UniqueID => uid ??= Interlocked.Increment(ref NextID);

    public override bool BooleanValue => true;

    public override bool IsObject => true;


    public JSObject() : base(null) { }

    internal protected JSObject(JSObject prototype = null) : base(prototype) { }

    public virtual IEnumerable<(string Key, JSValue value)> Entries
    {
        get
        {
            var es = GetElementEnumerator();

            while (es.MoveNext(out var hasValue, out var value, out var index))
            {
                if (hasValue)
                    yield return (index.ToString(), value);
            }

            var ownProperties = GetOwnProperties();
            var en = new PropertyValueEnumerator(this, false);

            while (en.MoveNext(out var value, out var key))
                yield return (KeyStrings.GetNameString(key.Key).Value, value);
        }
    }

    public JSObject(IEnumerable<JSProperty> entries) : this(GetCurrentObjectPrototype())
    {
        foreach (var p in entries)
            ownProperties.Put(p.key) = p;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithProperties() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithElements() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithPropertiesAndElements() => new JSObject { };

    private bool toStringCalled = false;

    public override double DoubleValue
    {
        get
        {
            try
            {
                var fx = this[KeyStrings.valueOf];
                if (fx.IsUndefined)
                    return CoerceToNumber(ToString());

                var v = fx.InvokeFunction(new Arguments(this));
                if (v == this)
                    return double.NaN;

                return v.DoubleValue;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                return double.NaN;
            }
        }
    }

    public override int Length
    {
        get
        {
            try
            {
                ref var ownp = ref ownProperties;
                if (ownp.IsEmpty)
                    return -1;

                ref var l = ref ownp.GetValue(KeyStrings.length.Key);
                if (!l.IsEmpty)
                {
                    var n = this.GetValue(l);
                    var nvalue = ((uint)n.DoubleValue) >> 0;
                    return (int)nvalue;
                }

                return -1;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                return -1;
            }
        }
        set
        {
            if (IsSealedOrFrozenOrNonExtensible())
                throw NewTypeError($"Cannot modify property length of {this}");

            ref var ownp = ref GetOwnProperties();
            ownp.Put(KeyStrings.length, JSValue.CreateNumber(value));
            PropertyChanged?.Invoke(this, (KeyStrings.length.Key, uint.MaxValue, null));
        }
    }
}
